project:
  title: "Kyle Biagan's Personal Website"
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience-projects.qmd
        text: Experience and Projects
      - href: education.qmd
        text: Education
      - href: skills.qmd
        text: Skills
      - href: résumé.qmd
        text: Résumé
    tools:
      - icon: linkedin
        href: https://www.linkedin.com/in/kylebiagan02/
      - icon: github
        href: https://github.com/kylebiagan02
  reader-mode: true
  back-to-top-navigation: true
  page-footer: "Copyright 2025, Kyle Biagan"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
