project:
  type: website

website:
  navbar:
    left:
      - text: "Kyle Biagan's Personal Website"
      - href: index.qmd
        text: Home
      - href: experience-projects.qmd
        text: Experience and Projects
      - href: education.qmd
        text: Education
      - href: skills.qmd
        text: Skills
      - href: résumé.qmd
        text: Résumé

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
