project:
  type: website

website:
  title: "Kyle Biagan Personal Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience-projects.qmd
        text: Experience and Projects
      - href: education-coursework.qmd
        text: Education and Coursework
      - href: skills.qmd
        text: Skills
      - href: résumé.qmd
        text: Résumé

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
