---
title: "EDUCATION AND COURSEWORK"
---

# Education
## University of California, Los Angeles (UCLA)
### BS in Statistics and Data Science
**Los Angeles, CA**
*September 2022 – June 2024*

#### Relevant Coursework:
COMPTNG 10A - Intro to Programming, DGT HUM 101 - Intro to Digital Humanities, MATH 42 - Intro to Data-Driven Mathematical Modeling: Life, Universe, and Everything, MATH 115A - Linear Algebra, MATH 131A - Analysis, STATS 15 - Intro to Data Science, STATS 21 - Python and Other Technologies for Data Science, STATS 100A - Intro to Probability, STATS 100B - Intro to Mathematical Statistics, STATS 100C - Linear Models, STATS 101A - Intro to Data Analysis and Regression, STATS 101B - Intro to Design and Analysis of Experiment, STATS 101C - Intro to Statistical Models and Data Mining, STATS 102A - Intro to Computational Statistics, STATS 102B - Intro to Computation and Optimization for Statistics, STATS 102C - Intro to Monte Carlo Methods, STATS 140XP/141XP - Practice of Statistical Consulting

## University of California, Santa Barbara (UCSB)
### BS in Financial Mathematics and Statistics
#### (Partially Completed, Transferred to UCLA)
**Santa Barbara, CA **
*October 2020 – June 2022*

#### Relevant Coursework:
CMPSC 8 - Intro to Computer Science, ECON 1 - Principles of Microeconomics, ECON 2 - Principles of Macroeconomics, ECON 3A/B - Financial Accounting, ECON 10A - Intermediate Microeconomic Theory, MATH 3A/B - Calculus with Applications, MATH 4A - Linear Algebra, MATH 4B - Differential Equations, MATH 6A/B - Vector Calculus with Applications, MATH 8 - Transition to Higher Mathematics, PSTAT 10 - Principles of Data Science with R

#### Achievements:
- College of Letters and Science Dean's Honors (Fall 2020, Winter 2021, Winter 2022)

- National Society of Collegiate Scholars (NSCS) Nomination (Winter 2021)

- National Society of Leadership and Success (NSLS) Nomination (Winter 2021)

