---
title: "EXPERIENCE AND PROJECTS"
---

# Professional Experience

## Administrative Data Entry Assistant
### The Arbor Dental Group
**Irvine, CA**
*July 2023 - September 2023*

Organized and maintained physical and electronic patient records to streamline retrieval and ensure data accuracy. Entered updated information into the office database, identified discrepancies, and supported the transition to a digital record-keeping system while preserving an accessible physical backup. Improved operational efficiency, reduced retrieval times, and enhanced data integrity.

## Estimating and Pricing Analyst Intern
### Boeing
**Tukwila, WA (Remote from Irvine, CA)**
*June 2022 - August 2022*

During Boeing's ten-week Summer 2022 Business Internship Program (BBIP) - Finance, interacted directly with company leaders to discuss finance, strategy, and the future of Boeing. Working with the Boeing Defense, Space & Security (BDS) P-8A Estimating and Pricing team provided an opportunity to apply education to meaningful projects while developing skills in financial acumen, data analytics, financial modeling, emotional intelligence, and problem-solving. Conducted data analysis of proposal requirements and developed actionable plans for compliant cost proposals, ensuring adherence to Federal Acquisition Regulations (FAR). Additionally, coordinated with cross-functional teams, including Estimating, Pricing, Procurement, Contracts, and Supply Chain, to optimize cost estimation methodologies and enhance proposal development workflows. The role also involved facilitating fact-finding and strategic negotiations, providing data transformation support that improved the accuracy of cost estimates and enhanced decision-making processes.

## Marketing and Public Relations Intern
### UCSB Men's Soccer
**Santa Barbara, CA (Hybrid)**
*October 2021 - June 2022*

Assisted the Marketing and Public Relations Coordinator in supervising community outreach programs, developing and implementing marketing plans to increase support and attendance for UCSB Men's Soccer games. Collaborated with the Associate Head Coach to design and photograph new material for the team's official recruiting website. Coordinated community outreach initiatives and crafted strategic marketing plans aimed at enhancing attendance and support for home games. Additionally, captured high-quality photographs of UCSB Men’s Soccer facilities, home games, and team-exclusive events, which improved marketing materials. This work ultimately elevated the digital presence of the UCSB Men's Soccer program.

# Projects

## Boeing
### PBOM Transmittal Memo
**Tukwila, WA (Remote from Irvine, CA)**
*June 2022 - August 2022*

Collaborated with Boeing’s BDS P-8A Estimating and Pricing team to streamline Material Estimate documentation by identifying and eliminating redundancies in the process. This optimization enhanced both efficiency and accuracy within the documentation workflow.

## UCSB Men's Soccer
### Gaucho Recruiting Zone Website
**Santa Barbara, CA (Hybrid)**
*October 2021 - June 2022*

Partnered with the Associate Head Coach of the UCSB Men's Soccer team to design, photograph, and maintain new content for the rebranded official recruiting website, now named "Gaucho Recruiting Zone." This project aimed to enhance the site's appeal and accessibility for prospective student-athletes. Leveraging HTML, the collaboration resulted in a more engaging platform that effectively showcases the program and its opportunities.

# Volunteer Experience

## Usher, Altar Server, and Fundraiser
### St. John Neumann Catholic Church
**Irvine, CA**
*August 2016 - Present*

Collaborate with a church ministry team to usher and altar serve during mass, ensuring a smooth and welcoming experience for parishioners. In addition, engage in fundraising efforts to support the church, assist priests, and provide resources for local children with physical and mental disabilities, fostering community support and outreach.

## Altar Server and Food Bank Worker
### St. Elizabeth Ann Seton Catholic Church
**Irvine, CA**
*August 2016 - Present*

Collaborate with a church ministry team to altar serve during Mass, contributing to a reverent and organized worship experience for the parishioners. Additionally, assist in delivering food from the Second Harvest Food Bank of Orange County to underprivileged families, ensuring they receive essential resources and support.
