---
title: "Work Experience"
---

# The Boeing Company
## Estimating and Pricing Analyst Intern
*June 2022 - August 2022*

During Boeing's ten-week Summer 2022 Business Internship Program (BBIP) - Finance, interacted directly with company leaders to discuss finance, strategy, and the future of Boeing. The Boeing
Defense, Space & Security (BDS) P-8A Estimating and Pricing team has helped me apply my education to meaningful projects while developing skills in financial acumen, data analytics, financial
modeling, emotional intelligence, and problem-solving.

# UCSB Men's Soccer Office
## Marketing and Public Relations Intern
*October 2021 - June 2022*

Assisted the Marketing and Public Relations Coordinator in supervising community outreach programs, developing and implementing marketing plans, and increasing support and attendance for Men's Soccer games. Worked with the Men's Soccer team's Associate Head Coach in designing and photographing new material for the team's official recruiting website.